import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import axios from "axios";
import TextField from "@mui/material/TextField";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import { weatherImg } from "../data/weatherData";

export default function Home() {
  const [location, setLocation] = useState("");
  const [data, setData] = useState("");
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState("");
  const [bg, setBg] = useState("01d");

  var apiKey = process.env.NEXT_PUBLIC_KEY;
  var lang = "en";
  var units = "metric";
  const url = `
  https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = (event) => {
    if (event.key === "Enter") {
      axios
        .get(url)
        .then((response) => {
          console.clear;
          setData(response.data);
          console.log(response.data);
          setWeather(response.data.weather);
          setBg(response.data.weather[0].icon);
          setErrorMessage("");
        })
        .catch((err) => {
          console.log(err);
          setErrorMessage("Please enter another location");
          setData("");
          setWeather();
          setBg("01d");
        });
      setLocation("");
    }
  };
  return (
    <div className="flex flex-col">
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="z-20"></Header>
      <div className="h-full -z-10">
        <div className="bg-raisin w-full h-full absolute z-10 opacity-20"></div>
        <img src={`${weatherImg[bg]}`} className="w-full h-full absolute"></img>
      </div>

      <main className="h-screen items-center p-4 flex flex-col justify-center align-middle">
        <div className="w-1/4  bg-snow rounded-md p-4 flex flex-col transition-all ">
          <TextField
            style={{ padding: 4 }}
            id="outlined-basic"
            label="Location"
            variant="outlined"
            value={location}
            onChange={(event) => setLocation(event.target.value)}
            placeholder="Enter Location"
            onKeyDown={searchLocation}
            type="text"
          />
          <div className=" mb-2 bg-snow rounded-md p-4 flex flex-col justify-center ">
            {errorMessage && <div className="text-xl text-raisin">{errorMessage}</div>}

            <div className="text-center text-4xl font-Heebo text-raisin">
              {" "}
              {data.name}{" "}
            </div>

            {weather && (
              <>
                {weather.map((w, index) => {
                  return (
                    <div
                      className="flex justify-center items-center"
                      key={index}
                    >
                      <img
                        className="w-16"
                        src={`http://openweathermap.org/img/wn/${w.icon}@2x.png`}
                      ></img>
                      <div>
                        <div className="text-xl text-raisin">{w.main}</div>
                        <div className="text-xl text-raisin">{w.description}</div>  
                      </div>

                     
                    </div>
                  );
                })}
                <div className="flex justify-center">
                  <div className="text-xl mr-2 text-raisin">
                    Temp: {data.main.temp}°C
                  </div>
                  <div className="ml-2 text-xl text-raisin">
                    Feels: {data.main.feels_like}°C
                  </div>
                </div>

               <div className="flex justify-center">
               {data.wind.gust ? (
                  <div className="text-xl text-raisin">Gust: {data.wind.gust}m/s</div>
                ) : (
                  <div className="text-xl text-raisin">Gust: No gust data found!</div>
                )}

               </div>
            
              </>
            )}
          </div>
        </div>
      </main>
      <Footer></Footer>
    </div>
  );
}
